name: Lets Start El
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "telethn"
          replace: "client"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'by me'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Oxidisedman
          commit_user_email: 72887386+Oxidisedman@users.noreply.github.com
          commit_author: Oxidisedman <72887386+OxidisedmanK@users.noreply.github.com>
